### PR TITLE
more post launch tweaks

### PR DESCRIPTION
**Pull request by LouiseSchuller**

### CODE REVIEW

**Review by benjiebeetle — DISMISSED** [review]
These look like exactly what's required!

**Review by azy141 — DISMISSED** [review]

**Comment by MarBuc** [comment]
@LouiseSchuller @benjiebeetle could we approve and merged if you are happy with this change so we can deploy etc...?
thanks

**Comment by LouiseSchuller** [comment]
Please do I'm waiting for the merge so I can check - all should be fully upto date

**Review by benjiebeetle — APPROVED** [review]
All good

**Pull request merged**
