### PR TITLE
Add UCL Logo Default Image

### PR DESCRIPTION
**Pull request by Manogar14996**
As discussed in the Dev drop in, the UCL logo is to be added to the indigo3 repo, so that it could be added to the CDN and be referred to by multiple different modules within the new UCL Indigo profile for the Alpha Pros.

### CODE REVIEW

**Comment by gideoncresswell** [comment]
Any chance we can get a much bigger version? The Guardian for example has this - https://assets.guim.co.uk/images/eada8aa27c12fe2d5afa3a89d3fbae0d/fallback-logo.png

**Comment by azy141** [comment]
Not sure if its just me but the image seems blurry `https://raw.githubusercontent.com/UCL-WAMS/indigo3/6fea6286617b6aab49a1169e7c48d49613a0e122/images/ucl-logo-default-image.png`

**Comment by Manogar14996** [comment]
> Not sure if its just me but the image seems blurry `https://raw.githubusercontent.com/UCL-WAMS/indigo3/6fea6286617b6aab49a1169e7c48d49613a0e122/images/ucl-logo-default-image.png`

Is there anyway of resizing it to the size of the Guardian logo, whilst keeping the image clean? I thought about changing it to a JPEG but not sure if that is the best solution.

**Comment by azy141** [comment]
> 
> 
> > Not sure if its just me but the image seems blurry `https://raw.githubusercontent.com/UCL-WAMS/indigo3/6fea6286617b6aab49a1169e7c48d49613a0e122/images/ucl-logo-default-image.png`
> 
> Is there anyway of resizing it to the size of the Guardian logo, whilst keeping the image clean? I thought about changing it to a JPEG but not sure if that is the best solution.

We must have a larger source image somewhere that can be shrank down. Otherwise Louise might be able to generate one for you in the exact size you need?

**Comment by MarBuc** [comment]
HI team, adding Louise so she is also aware of this change and can chip in if needed.

**Comment by LouiseSchuller** [comment]
What's this logo going to be used for and where was it sourced form ?  It's not the logo that CL have specified in their figma file (in their version there is no white block below the logo) I am in the process of trying to get some high quality new versions made using their spec for the new templates.  So this should probably be regarded as a placeholder for now if it's going to be used.

**Comment by Manogar14996** [comment]
> What's this logo going to be used for and where was it sourced form ? It's not the logo that CL have specified in their figma file (in their version there is no white block below the logo) I am in the process of trying to get some high quality new versions made using their spec for the new templates. So this should probably be regarded as a placeholder for now if it's going to be used.

This logo is planned to be used as the default image for the featured image field for content types within the Alpha Prospectus. As for the source I am not completely sure as I got the image from @azy141 , so Aaron if you could please add the image source if you still have it, it would be much appreciated. I am more than happy for this to be a placeholder for now, since it should require no coding changes to replace this logo with the official one we will use.

**Comment by azy141** [comment]
I got the logo from the SVG https://github.com/UCL-WAMS/indigo/blob/master/images/ucl-logo.svg and edited it to match as closely as I could this https://github.com/UCL-WAMS/indigo/blob/master/images/twitter-card-ucl-logo.png just at a higher resolution.

**Comment by LouiseSchuller** [comment]
Thanks Aaron and Manny - yes that looks fine - I think it will be ok to use this for now. If you can give me a headsup if you do use it anywhere for the new templates that would be appreciated.  Also, there is a set of sized up logo asset files, in skins at \skins\ucl-brand-assets for next time you need good copies of the current logo.

**Review by gideoncresswell — APPROVED** [review]

**Pull request merged**
