### PR TITLE
[DP-2789] Fix 5 card layout on mobile

### PR DESCRIPTION
**Pull request by Sem-the-dev**

### CODE REVIEW

**Comment by LouiseSchuller** [comment]
Why has this file been submitted
 sass/indigo3.scss 
This is the sass file that calls the partials and should'nt need to be touched for this job.  Changing it will affect the cascade of the whole css codebase
The same partial has been called twice and the location of the semi colon will break the sass complation

**Comment by LouiseSchuller** [comment]
In firefox and chrome I can still see a 48px margin to the left and right
The story specifys a 16px margin/padding to the left and right.  The extra padding is on the component and needs to be removed.

image

**Comment by LouiseSchuller** [comment]
The is also a conflict on the css/indigo3.min.css for this pull request that will need to be resolved.

**Comment by Sem-the-dev** [comment]
> In firefox and chrome I can still see a 48px margin to the left and right when I use this version of indigo3.css.min The story specifys a 16px margin/padding to the left and right. The extra padding is on the component and needs to be removed.
> 
> image

I have left the min file as I thought I shouldn't touch it, happy to accept changes it going forward

**Comment by Sem-the-dev** [comment]
> Why has this file been submitted? sass/indigo3.scss This is the sass file that calls the partials and should'nt need to be touched for this job. Changing it will affect the cascade of the whole css codebase The same partial has been called twice and the location of the semi colon will break the sass complation
> 
> 

I was getting error messages because there was a semi colon missing

**Comment by Sem-the-dev** [comment]
> In firefox and chrome I can still see a 48px margin to the left and right when I use this version of indigo3.css.min The story specifys a 16px margin/padding to the left and right. The extra padding is on the component and needs to be removed.
> 
> image

Now I've updated the min file, does it still show 48px?

**Comment by LouiseSchuller** [comment]
Minified css files
Server css files are min files as standard.
Once the code is correct this is the file that will need to be deployed to the cdn.
https://cdn.ucl.ac.uk/indigo3/css/indigo3.min.css

You can see the link to the cdn file in all template heads
search indigo3.css

<link type="text/css" rel="stylesheet" href="//cdn.ucl.ac.uk/indigo3/css/indigo3.min.css?r3c6v8" media="all" />

Is you sass compiling the min file at the same time as the unminified css file?
If not it should.
---------------------------------------------------------------------------------------
Padding -

The extra padding is still on the left and right margins in mobile
image
To remove  do the following

Apart from the change to the media query to md - remove all your changes


Base styles ....

Add container  padding 0 to the base styles of  the five card layout 
ie

.five-card-layout {
	margin-top: 1.8rem;
	margin-bottom: 1.5rem;
	container {
		padding: 0;
	}
	
	
remove 


.five-card__right {
	order: 2;
	.card {
		margin-bottom: 2rem;
	}
}

change padding to margin bottom 0

.five-card__left-top {
	order: 1;
	padding-bottom: 0 1rem 1.875rem 1rem;

Remove all rules and comments associated with this in base style and add margin 0
.six-by-six__left,
.six-by-six__right {
    margin-bottom: 0;
}

Breakpoint md styles

Remove all  of this.
Why have you repeated the breakpoint? - this is confusing and has the potential to cause conflicts in the cascade
Using .site-prospective-students-graduate means only five card components on this site will be updated with these rules.

@include media-breakpoint-up(md) {
	.six-by-six__left,
	.six-by-six__right {
		padding-right: 1rem;
		padding-left: 1rem;
		max-width: 50%;
	}
}

.site-prospective-students-graduate section.section-five-item h1.field-paragraph-heading   {
	margin-left: 30px;
}

Remove this  see comment above for site specific selector.
 .site-prospective-students-graduate section.section-five-item h1.field-paragraph-heading   {
	 margin-left: 0;
 }

---------------------------------------------------------------------

The complete sass (check against the page appearance !)


/*------------------
FIVE CARD LAYOUT
----------------------------*/

.five-card-layout {
	margin-top: 1.8rem;
	margin-bottom: 1.5rem;
	.container {
		padding: 0;
	}

	.card__icon {
		display: none;
	}

	.five-card__right {
		order: 2;
	
	}

	.five-card__left-top {
		order: 1;
		margin-bottom: 0;

		div.field-content-summary {
			font-size: 1.125rem;
		}
	}

	.five-card__left-bottom {
		order: 3;
		border-top: solid 1px #d6d6d6;
		padding-top: 2.1875rem;
		width: 100%;

		h2 {
			border: none;
			padding-top: 0;
			margin-top: 0;
		}
	}

	.field-content-summary {
		margin-bottom: 1.5rem;
	}

	.six-by-six__left,
	.six-by-six__right {
	    margin-bottom: 0;
	}


}


 @include media-breakpoint-up(md) {


.five-card {

	.card__icon {
		display:none;
	}
	.float.row {
  		display: block;
  	}
	.five-card__right {
	float: right; 
	width: 50%;
	
	}
	.five-card__right .six-by-six__left {
 			border-right: solid 1px $pxlinegraylight;
 			border-left: solid 1px $pxlinegraylight;
 			padding-left: 1rem;
 			padding-right: 1rem; 
 			 }
 	.five-card__right .six-by-six__right {
 			padding-left: 1rem;
 			padding-right: 1rem;
 	}
	.five-card__left-top {
		float: left; 
		width: 50%; 
		padding-right: 1.25rem;
		padding-left: 0; 
		.card {
			border-bottom: solid 1px $pxlinegraylight;
		}
	}
	.card { 
		margin-bottom: 15px;
	}
	.five-card__left-bottom  {
		float: left; 
		width: 50%; 
		clear: left; 
		padding-right: 1.25rem; 
		border-top: 0;
		padding-top: 0;
	   .six-by-six__left {
	   	padding-left: 0;
	   }
	}
}

}

**Review by LouiseSchuller — APPROVED** [review]
All looks good on my local

**Pull request merged**
